INSERT OR REPLACE INTO EnglishText (Tag, Text) VALUES
    ('LOC_TECH_POTTERY_DESCRIPTION', 'Allows harvesting of [ICON_RESOURCE_WHEAT] Wheat, [ICON_RESOURCE_RICE] Rice, and [ICON_RESOURCE_MAIZE] Maize.'),
    ('LOC_TECH_ANIMAL_HUSBANDRY_DESCRIPTION', 'Allows harvesting of [ICON_RESOURCE_CATTLE] Cattle, [ICON_RESOURCE_SHEEP] Sheep, and [ICON_RESOURCE_DEER] Deer.'),
    ('LOC_TECH_MINING_DESCRIPTION', 'Allows chopping of Woods, and harvesting of [ICON_RESOURCE_Copper] Copper.'),
    ('LOC_TECH_SAILING_DESCRIPTION', 'Allows Builders to embark.'),
    ('LOC_TECH_IRRIGATION_DESCRIPTION', 'Allows clearing of Marsh, and harvesting of [ICON_RESOURCE_BANANAS] Bananas.'),
    ('LOC_TECH_MASONRY_DESCRIPTION', 'Allows harvesting of [ICON_RESOURCE_STONE] Stone.'),
    ('LOC_TECH_BRONZE_WORKING_DESCRIPTION', 'Allows chopping of Rainforest.'),
    ('LOC_TECH_CELESTIAL_NAVIGATION_DESCRIPTION', 'Allows Traders to embark, and allows harvesting of [ICON_RESOURCE_FISH] Fish and [ICON_RESOURCE_CRABS] Crabs.'),
    ('LOC_TECH_SHIPBUILDING_DESCRIPTION', 'Allows all land units to embark.'),
    ('LOC_TECH_MATHEMATICS_DESCRIPTION', '+1 [ICON_Movement] Movement for all naval units.'),
    ('LOC_TECH_APPRENTICESHIP_DESCRIPTION', '+1 [ICON_Production] Production on Mine.'),
    ('LOC_TECH_STIRRUPS_DESCRIPTION', '+1 [ICON_Food] Food on Pasture.'),
    ('LOC_TECH_CARTOGRAPHY_DESCRIPTION', '+2 [ICON_Gold] Gold on Fishing Boats. All naval and embarked units can navigate Ocean.'),
    ('LOC_TECH_GUNPOWDER_DESCRIPTION', '+1 [ICON_Production] Production on Quarry.'),
    ('LOC_TECH_PRINTING_DESCRIPTION', 'Provides +1 level of diplomatic visibility on all other civilizations. +100% [ICON_Tourism] Tourism from [ICON_GreatWork_Writing] Great Work of Writing.'),
    ('LOC_TECH_SQUARE_RIGGING_DESCRIPTION', '+1 [ICON_Movement] Movement for embarked units.'),
    ('LOC_TECH_INDUSTRIALIZATION_DESCRIPTION', '+1 [ICON_Production] Production on Mine.'),
    ('LOC_TECH_SCIENTIFIC_THEORY_DESCRIPTION', '+1 [ICON_Food] Food on Plantation.'),
    ('LOC_TECH_STEAM_POWER_DESCRIPTION', '+2 [ICON_Movement] Movement for embarked units.'),
    ('LOC_TECH_FLIGHT_DESCRIPTION', 'Receive [ICON_Tourism] Tourism on all improvements, equal to their [ICON_Culture] Culture output.'),
    ('LOC_TECH_REPLACEABLE_PARTS_DESCRIPTION', '+1 [ICON_Food] Food for every adjacent Farm on Farm. +1 [ICON_Production] Production on Pasture.'),
    ('LOC_TECH_STEEL_DESCRIPTION', '+1 [ICON_Production] Production on Lumber Mill. All cities receive 400 Fortification Strength and are not affected by Siege Towers or Battering Rams.'),
    ('LOC_TECH_ROCKETRY_DESCRIPTION', '+1 [ICON_Production] Production on Quarry.'),
    ('LOC_TECH_COMPUTERS_DESCRIPTION', 'Grants the ability to train an additional Spy. +25% [ICON_Tourism] Tourism across your civilization.'),
    ('LOC_TECH_ROBOTICS_DESCRIPTION', '+1 [ICON_Food] Food on Pasture.'),
    ('LOC_TECH_ADVANCED_AI_DESCRIPTION', 'Unlocks Giant Death Robot upgrade: Drone Air Defense (+100 [ICON_AntiAir_Large] Anti-Air Strength).'),
    ('LOC_TECH_ADVANCED_POWER_CELLS_DESCRIPTION', 'CO2 emissions from units reduced by 50%. Unlocks Giant Death Robot upgrade: Particle Beam Siege Cannon (Ranged attacks against district defenses are 100% effective and gain +30 [ICON_Ranged] Ranged Strength.)'),
    ('LOC_TECH_SMART_MATERIALS_DESCRIPTION', '+1 [ICON_Production] Production on Mine. Unlocks Giant Death Robot upgrade: Reinforced Armor Plating (+10 [ICON_Strength] Combat Strength when defending against land and naval units.)'),
    ('LOC_TECH_CYBERNETICS_DESCRIPTION', '+1 [ICON_Production] Production on Lumber Mill. Unlocks Giant Death Robot upgrade: Enhanced Mobility (+3 [ICON_Movement] Movement. Can perform Jump action to cross over mountain.)'),
    ('LOC_TECH_PREDICTIVE_SYSTEMS_DESCRIPTION', '+1 [ICON_Production] Production on Quarry, Oil Well, and Offshore Oil Rig.'),
    ('LOC_TECH_SEASTEADS_DESCRIPTION', 'Awards 1 Diplomatic Victory point.');
