INSERT OR REPLACE INTO EnglishText (Tag, Text) VALUES
	('LOC_DISTRICT_HARBOR_EXPANSION1_DESCRIPTION', 'A district for naval activity in your city. No [ICON_Movement] Movement penalty for embarking and disembarking. Must be built on Coast or Lake adjacent to land. Cannot be built on Reef.'),
	('LOC_DISTRICT_ENTERTAINMENT_COMPLEX_DESCRIPTION', 'A district in your city dedicated to keeping your people happy. Cannot be built in a city with Water Park district.'),
	('LOC_DISTRICT_WATER_ENTERTAINMENT_COMPLEX_DESCRIPTION', 'A district placed on water dedicated to keeping your people happy. Must be built on Coast or Lake adjacent to land. Cannot be built in a city with Entertainment Complex district. Cannot be built on Reef.'),
	('LOC_DISTRICT_AQUEDUCT_ALT_DESCRIPTION', 'A district that provides extra fresh water from adjacent water source. Cities with existing fresh water get +2 [ICON_Housing] Housing, and other cities get +1 [ICON_Housing] Housing in addition to full [ICON_Housing] Housing from fresh water. +1 [ICON_Amenities] Amenity if adjacent to Geothermal Fissure. Prevents [ICON_Food] Food loss during Drought.'),
	('LOC_DISTRICT_DAM_DESCRIPTION', 'A district built on Floodplains to improve the comfort of living along this river. Prevents damage from flooding of this river (though yields from flooding drop by 50%). Prevents [ICON_Food] Food loss during Drought.'),
	('LOC_DISTRICT_CANAL_DESCRIPTION', 'A district built on flat land to connect two bodies of water or a body of water to City Center.'),
	('LOC_DISTRICT_NEIGHBORHOOD_DESCRIPTION', 'A district that provides up to 6 [ICON_Housing] Housing based on Appeal.'),
	('LOC_DISTRICT_PRESERVE_DESCRIPTION', 'A district for protecting natural environment. Grants up to 3 [ICON_Housing] Housing based on Appeal. Culture bombs adjacent neutral tiles.'),
	('LOC_DISTRICT_SPACEPORT_DESCRIPTION_XP2', 'A district that is required to construct the Science Victory projects. Cannot be built on Hills.'),
	('LOC_DISTRICT_GOVERNMENT_DESCRIPTION', 'A district placed once in your civilization to commemorate your government choices. Provides +8 Loyalty per turn to this city. Awards +1 [Icon_Governor] Governor Title.'),
	('LOC_DISTRICT_DIPLOMATIC_QUARTER_EXPANSION2_DESCRIPTION', 'A district placed once in your civilization to facilitate international diplomacy. Grants +1 [ICON_FAVOR] Diplomatic Favor for each Delegation or Embassy from other civilizations. Awards +1 [ICON_Envoy] Envoy if built next to City Center. Enemy Spies operate at 2 levels below normal when targeting this district or adjacent districts.');
