INSERT OR REPLACE INTO EnglishText (Tag, Text) VALUES
    ('LOC_CIVIC_FOREIGN_TRADE_DESCRIPTION', 'Allows creation of [ICON_TradeRoute] Trade Routes.'),
    ('LOC_CIVIC_MILITARY_TRAINING_DESCRIPTION', 'Grants flanking and support combat bonuses to all combat units.'),
    ('LOC_CIVIC_EARLY_EMPIRE_DESCRIPTION', 'Unlocks the abilities to enforce borders.'),
    ('LOC_CIVIC_FEUDALISM_DESCRIPTION', '+1 [ICON_Food] Food for every 2 adjacent Farms on Farm. +1 [ICON_Food] Food on Plantation.'),
    ('LOC_CIVIC_DIPLOMATIC_SERVICE_DESCRIPTION', 'Grants the ability to train a Spy.'),
    ('LOC_CIVIC_MERCANTILISM_DESCRIPTION', '+1 [ICON_Production] Production and +1 [ICON_Food] Food on Camp. Can build Lumber Mill on Rainforest.'),
    ('LOC_CIVIC_THE_ENLIGHTENMENT_DESCRIPTION', 'Religious [ICON_Tourism] Tourism is halved against your civilization.'),
    ('LOC_CIVIC_COLONIALISM_DESCRIPTION', '+1 [ICON_Production] Production on Fishing Boats.'),
    ('LOC_CIVIC_CIVIL_ENGINEERING_DESCRIPTION', 'Can build Farm on Grassland Hills and Plains Hills.'),
    ('LOC_CIVIC_NATIONALISM_DESCRIPTION', 'Grants the ability to train an additional Spy. Allows forming two identical units into a Corps or Fleet.'),
    ('LOC_CIVIC_CONSERVATION_DESCRIPTION', 'Can build National Park. Allows Builders to plant Woods (second-growth). +1 Appeal to original Woods in your civilization (old-growth). Receive [ICON_TOURISM] Tourism from Walls.'),
    ('LOC_CIVIC_MOBILIZATION_DESCRIPTION', 'Allows forming three identical units into an Army or Armada.'),
    ('LOC_CIVIC_IDEOLOGY_DESCRIPTION', 'Grants the ability to train an additional Spy.'),
    ('LOC_CIVIC_COLD_WAR_DESCRIPTION', 'Grants the ability to train an additional Spy.'),
    ('LOC_CIVIC_RAPID_DEPLOYMENT_DESCRIPTION', 'Allows transportation of land units between Airport Building.'),
    ('LOC_CIVIC_ENVIRONMENTALISM_DESCRIPTION', '+25% [ICON_Tourism] Tourism across your civilization.'),
    ('LOC_CIVIC_GLOBALIZATION_DESCRIPTION', '+2 [ICON_Gold] Gold on Plantation.'),
    ('LOC_CIVIC_GLOBAL_WARMING_MITIGATION_DESCRIPTION', 'Awards 1 Diplomatic Victory point.');
