UPDATE Districts SET CitizenSlots=1	WHERE DistrictType='DISTRICT_INDUSTRIAL_ZONE' OR DistrictType='DISTRICT_HANSA' OR DistrictType='DISTRICT_OPPIDUM';
UPDATE Districts SET CitizenSlots=1	WHERE DistrictType='DISTRICT_COMMERCIAL_HUB' OR DistrictType='DISTRICT_SUGUBA';
UPDATE Districts SET CitizenSlots=1	WHERE DistrictType='DISTRICT_CAMPUS' OR DistrictType='DISTRICT_OBSERVATORY';
UPDATE Districts SET CitizenSlots=2	WHERE DistrictType='DISTRICT_SEOWON';
UPDATE Districts SET CitizenSlots=1	WHERE DistrictType='DISTRICT_THEATER' OR DistrictType='DISTRICT_ACROPOLIS';
UPDATE Districts SET CitizenSlots=1	WHERE DistrictType='DISTRICT_HOLY_SITE' OR DistrictType='DISTRICT_LAVRA';

UPDATE Districts SET CitizenSlots=1	WHERE DistrictType='DISTRICT_ENCAMPMENT' OR DistrictType='DISTRICT_IKANDA' OR DistrictType='DISTRICT_THANH';
UPDATE Districts SET CitizenSlots=1	WHERE DistrictType='DISTRICT_HARBOR' OR DistrictType='DISTRICT_ROYAL_NAVY_DOCKYARD' OR DistrictType='DISTRICT_COTHON';
UPDATE Districts SET CitizenSlots=1	WHERE DistrictType='DISTRICT_AERODROME';
UPDATE Districts SET CitizenSlots=1	WHERE DistrictType='DISTRICT_ENTERTAINMENT_COMPLEX' OR DistrictType='DISTRICT_STREET_CARNIVAL';
UPDATE Districts SET CitizenSlots=1	WHERE DistrictType='DISTRICT_WATER_ENTERTAINMENT_COMPLEX' OR DistrictType='DISTRICT_WATER_STREET_CARNIVAL';
UPDATE Districts SET CitizenSlots=1	WHERE DistrictType='DISTRICT_NEIGHBORHOOD';
UPDATE Districts SET CitizenSlots=2	WHERE DistrictType='DISTRICT_MBANZA';
UPDATE Districts SET CitizenSlots=1	WHERE DistrictType='DISTRICT_GOVERNMENT';
UPDATE Districts SET CitizenSlots=1	WHERE DistrictType='DISTRICT_DIPLOMATIC_QUARTER';

UPDATE Buildings SET CitizenSlots=1	WHERE PrereqDistrict='DISTRICT_AERODROME';
UPDATE Buildings SET CitizenSlots=1	WHERE PrereqDistrict='DISTRICT_ENTERTAINMENT_COMPLEX' OR PrereqDistrict='DISTRICT_STREET_CARNIVAL';
UPDATE Buildings SET CitizenSlots=1	WHERE PrereqDistrict='DISTRICT_WATER_ENTERTAINMENT_COMPLEX' OR PrereqDistrict='DISTRICT_WATER_STREET_CARNIVAL';
UPDATE Buildings SET CitizenSlots=1	WHERE PrereqDistrict='DISTRICT_NEIGHBORHOOD' OR PrereqDistrict='DISTRICT_MBANZA';
UPDATE Buildings SET CitizenSlots=1	WHERE PrereqDistrict='DISTRICT_GOVERNMENT';
UPDATE Buildings SET CitizenSlots=1	WHERE PrereqDistrict='DISTRICT_DIPLOMATIC_QUARTER';

DELETE FROM District_CitizenYieldChanges WHERE DistrictType IS NOT NULL;
INSERT INTO District_CitizenYieldChanges(DistrictType, YieldType, YieldChange) VALUES
		('DISTRICT_INDUSTRIAL_ZONE',			'YIELD_PRODUCTION',	2),		
		('DISTRICT_COMMERCIAL_HUB',				'YIELD_FOOD',		1),
		('DISTRICT_COMMERCIAL_HUB',				'YIELD_GOLD',		2),		
		('DISTRICT_CAMPUS',						'YIELD_FOOD',		1),
		('DISTRICT_CAMPUS',						'YIELD_SCIENCE',	1),		
		('DISTRICT_THEATER',					'YIELD_FOOD',		1),
		('DISTRICT_THEATER',					'YIELD_CULTURE',	1),		
		('DISTRICT_HOLY_SITE',					'YIELD_FOOD',		1),
		('DISTRICT_HOLY_SITE',					'YIELD_FAITH',		1),
		
		('DISTRICT_ENCAMPMENT',					'YIELD_PRODUCTION',	1),
		('DISTRICT_ENCAMPMENT',					'YIELD_CULTURE',	1),		
		('DISTRICT_HARBOR',						'YIELD_GOLD',		2),
		('DISTRICT_HARBOR',						'YIELD_SCIENCE',	1),		
		('DISTRICT_AERODROME',					'YIELD_SCIENCE',	1),
		('DISTRICT_AERODROME',					'YIELD_CULTURE',	1),		
		('DISTRICT_ENTERTAINMENT_COMPLEX',		'YIELD_FOOD',		2),
		('DISTRICT_WATER_ENTERTAINMENT_COMPLEX','YIELD_FOOD',		2),		
		('DISTRICT_NEIGHBORHOOD',				'YIELD_FOOD',		2),
		('DISTRICT_NEIGHBORHOOD',				'YIELD_PRODUCTION',	1),		
		('DISTRICT_GOVERNMENT',					'YIELD_FOOD',		1),
		('DISTRICT_GOVERNMENT',					'YIELD_PRODUCTION',	1),
		('DISTRICT_GOVERNMENT',					'YIELD_GOLD',		2),
		('DISTRICT_DIPLOMATIC_QUARTER',			'YIELD_FOOD',		1),
		('DISTRICT_DIPLOMATIC_QUARTER',			'YIELD_PRODUCTION',	1),
		('DISTRICT_DIPLOMATIC_QUARTER',			'YIELD_GOLD',		2);
INSERT INTO District_CitizenYieldChanges(DistrictType, YieldType, YieldChange) SELECT a.CivUniqueDistrictType, b.YieldType, b.YieldChange FROM DistrictReplaces a, District_CitizenYieldChanges b WHERE a.ReplacesDistrictType=b.DistrictType AND b.DistrictType=a.ReplacesDistrictType;

DELETE FROM Building_CitizenYieldChanges WHERE BuildingType IS NOT NULL;
INSERT INTO Building_CitizenYieldChanges(BuildingType, YieldType, YieldChange) VALUES
		('BUILDING_WORKSHOP',					'YIELD_PRODUCTION',	1),
		('BUILDING_FACTORY',					'YIELD_PRODUCTION',	1),
		('BUILDING_COAL_POWER_PLANT',			'YIELD_PRODUCTION',	2),
		('BUILDING_FOSSIL_FUEL_POWER_PLANT',	'YIELD_PRODUCTION',	2),
		('BUILDING_POWER_PLANT',				'YIELD_PRODUCTION',	2),
		
		('BUILDING_MARKET',						'YIELD_GOLD',		2),
		('BUILDING_BANK',						'YIELD_GOLD',		2),
		('BUILDING_STOCK_EXCHANGE',				'YIELD_GOLD',		4),

		('BUILDING_LIBRARY',					'YIELD_SCIENCE',	1),
		('BUILDING_UNIVERSITY',					'YIELD_SCIENCE',	1),
		('BUILDING_RESEARCH_LAB',				'YIELD_SCIENCE',	2),
		
		('BUILDING_AMPHITHEATER',				'YIELD_CULTURE',	1),
		('BUILDING_MUSEUM_ART',					'YIELD_CULTURE',	1),
		('BUILDING_MUSEUM_ARTIFACT',			'YIELD_CULTURE',	1),
		('BUILDING_BROADCAST_CENTER',			'YIELD_CULTURE',	2),
		
		('BUILDING_SHRINE',						'YIELD_FAITH',		1),
		('BUILDING_TEMPLE',						'YIELD_FAITH',		1),
		('BUILDING_CATHEDRAL',					'YIELD_FAITH',		2),
		('BUILDING_DAR_E_MEHR',					'YIELD_FAITH',		2),
		('BUILDING_GURDWARA',					'YIELD_FAITH',		2),
		('BUILDING_MEETING_HOUSE',				'YIELD_FAITH',		2),
		('BUILDING_MOSQUE',						'YIELD_FAITH',		2),
		('BUILDING_PAGODA',						'YIELD_FAITH',		2),
		('BUILDING_STUPA',						'YIELD_FAITH',		2),
		('BUILDING_SYNAGOGUE',					'YIELD_FAITH',		2),
		('BUILDING_WAT',						'YIELD_FAITH',		2),
		
		('BUILDING_BARRACKS',					'YIELD_FOOD',		1),
		('BUILDING_STABLE',						'YIELD_FOOD',		1),
		('BUILDING_ARMORY',						'YIELD_PRODUCTION',	1),
		('BUILDING_MILITARY_ACADEMY',			'YIELD_FOOD',		1),
		('BUILDING_MILITARY_ACADEMY',			'YIELD_CULTURE',	1),
		
		('BUILDING_LIGHTHOUSE',					'YIELD_FOOD',		1),
		('BUILDING_SHIPYARD',					'YIELD_GOLD',		2),
		('BUILDING_SEAPORT',					'YIELD_FOOD',		1),
		('BUILDING_SEAPORT',					'YIELD_SCIENCE',	1),
		
		('BUILDING_HANGAR',						'YIELD_FOOD',		2),
		('BUILDING_AIRPORT',					'YIELD_SCIENCE',	1),
		('BUILDING_AIRPORT',					'YIELD_CULTURE',	1),
		
		('BUILDING_ARENA',						'YIELD_CULTURE',	1),
		('BUILDING_ZOO',						'YIELD_SCIENCE',	1),
		('BUILDING_STADIUM',					'YIELD_FOOD',		1),
		('BUILDING_STADIUM',					'YIELD_GOLD',		2),
		
		('BUILDING_FERRIS_WHEEL',				'YIELD_CULTURE',	1),
		('BUILDING_AQUARIUM',					'YIELD_SCIENCE',	1),
		('BUILDING_AQUATICS_CENTER',			'YIELD_FOOD',		1),
		('BUILDING_AQUATICS_CENTER',			'YIELD_GOLD',		2),
		
		('BUILDING_FOOD_MARKET',				'YIELD_FOOD',		1),
		('BUILDING_FOOD_MARKET',				'YIELD_PRODUCTION',	1),
		('BUILDING_FOOD_MARKET',				'YIELD_GOLD',		2),
		('BUILDING_SHOPPING_MALL',				'YIELD_FOOD',		1),
		('BUILDING_SHOPPING_MALL',				'YIELD_PRODUCTION',	1),
		('BUILDING_SHOPPING_MALL',				'YIELD_GOLD',		2),
		
		('BUILDING_GOV_TALL',					'YIELD_CULTURE',	1),
		('BUILDING_GOV_WIDE',					'YIELD_SCIENCE',	1),
		('BUILDING_GOV_CONQUEST',				'YIELD_FAITH',		1),
		
		('BUILDING_GOV_CITYSTATES',				'YIELD_CULTURE',	2),
		('BUILDING_GOV_SPIES',					'YIELD_SCIENCE',	2),
		('BUILDING_GOV_FAITH',					'YIELD_FAITH',		2),
		('BUILDING_QUEENS_BIBLIOTHEQUE',		'YIELD_CULTURE',	1),
		('BUILDING_QUEENS_BIBLIOTHEQUE',		'YIELD_SCIENCE',	1),
		('BUILDING_QUEENS_BIBLIOTHEQUE',		'YIELD_FAITH',		1),
		
		('BUILDING_GOV_CULTURE',				'YIELD_CULTURE',	2),
		('BUILDING_GOV_CULTURE',				'YIELD_FAITH',		1),
		('BUILDING_GOV_SCIENCE',				'YIELD_SCIENCE',	2),
		('BUILDING_GOV_SCIENCE',				'YIELD_CULTURE',	1),
		('BUILDING_GOV_MILITARY',				'YIELD_FAITH',		2),
		('BUILDING_GOV_MILITARY',				'YIELD_SCIENCE',	1),
		
		('BUILDING_CONSULATE',					'YIELD_CULTURE',	1),
		('BUILDING_CONSULATE',					'YIELD_FAITH',		1),
		('BUILDING_CHANCERY',					'YIELD_SCIENCE',	2),
		('BUILDING_CHANCERY',					'YIELD_CULTURE',	1),
		('BUILDING_CHANCERY',					'YIELD_FAITH',		1);
INSERT INTO Building_CitizenYieldChanges(BuildingType, YieldType, YieldChange) SELECT a.CivUniqueBuildingType, b.YieldType, b.YieldChange FROM BuildingReplaces a, Building_CitizenYieldChanges b WHERE a.ReplacesBuildingType=b.BuildingType AND b.BuildingType=a.ReplacesBuildingType;