UPDATE Technologies SET Description=null WHERE TechnologyType='TECH_CASTLES';
UPDATE Technologies SET Description=null WHERE TechnologyType='TECH_SANITATION';
UPDATE Technologies SET Description=null WHERE TechnologyType='TECH_SQUARE_RIGGING';
UPDATE Technologies SET Description='LOC_TECH_SQUARE_RIGGING_DESCRIPTION' WHERE TechnologyType='TECH_ASTRONOMY';
DELETE FROM TechnologyModifiers WHERE TechnologyType='TECH_SQUARE_RIGGING' AND ModifierId='SQUARE_RIGGING_ADJUST_EMBARKED_MOVEMENT';
INSERT INTO TechnologyModifiers(TechnologyType, ModifierId) VALUES
	('TECH_ASTRONOMY', 'SQUARE_RIGGING_ADJUST_EMBARKED_MOVEMENT');

UPDATE ModifierArguments SET Value='20' WHERE ModifierId='COMPUTERS_BOOST_ALL_TOURISM' AND Name='Amount';
UPDATE ModifierArguments SET Value='30' WHERE ModifierId='ENVIRONMENTALISM_BOOST_ALL_TOURISM' AND Name='Amount';

UPDATE Resource_Harvests SET PrereqTech = 'TECH_SAILING' WHERE ResourceType='RESOURCE_FISH';
UPDATE Resource_Harvests SET PrereqTech = 'TECH_SAILING' WHERE ResourceType='RESOURCE_CRABS';

UPDATE Technologies SET Description='LOC_TECH_GUIDANCE_SYSTEMS_DESCRIPTION' WHERE TechnologyType='TECH_GUIDANCE_SYSTEMS';
UPDATE Technologies SET Description='LOC_TECH_NUCLEAR_FUSION_DESCRIPTION' WHERE TechnologyType='TECH_NUCLEAR_FUSION';
UPDATE Technologies SET Description='LOC_TECH_COMPOSITES_DESCRIPTION' WHERE TechnologyType='TECH_COMPOSITES';
UPDATE Technologies SET Description='LOC_TECH_LASERS_DESCRIPTION' WHERE TechnologyType='TECH_LASERS';
UPDATE Technologies SET Description='LOC_TECH_NANOTECHNOLOGY_DESCRIPTION' WHERE TechnologyType='TECH_NANOTECHNOLOGY';
