INSERT OR REPLACE INTO EnglishText (Tag, Text) VALUES
    ('LOC_PROMOTION_RANGER_DESCRIPTION', 'Faster [ICON_Movement] Movement in Woods and Rainforest.'),
    ('LOC_PROMOTION_ALPINE_DESCRIPTION', 'Faster [ICON_Movement] Movement on Hills.'),
    ('LOC_PROMOTION_SENTRY_DESCRIPTION', 'Can see through Woods and Rainforest.'),
    ('LOC_PROMOTION_GUERRILLA_DESCRIPTION', 'Can move after attacking.'),
    ('LOC_PROMOTION_SPYGLASS_DESCRIPTION', '+1 sight range.'),
    ('LOC_PROMOTION_AMBUSH_DESCRIPTION', '+20 [ICON_Strength] Combat Strength.'),
    ('LOC_PROMOTION_CAMOUFLAGE_DESCRIPTION', 'Only adjacent enemy unit can reveal this unit.'),
    ('LOC_PROMOTION_BATTLECRY_DESCRIPTION', '+7 [ICON_Strength] Combat Strength when attacking melee, ranged, or anti-cavalry unit.'),
    ('LOC_PROMOTION_TORTOISE_DESCRIPTION', '+10 [ICON_Strength] Combat Strength when defending against ranged attack.'),
    ('LOC_PROMOTION_COMMANDO_DESCRIPTION', '+1 [ICON_Movement] Movement. Can scale Cliffs.'),
    ('LOC_PROMOTION_AMPHIBIOUS_DESCRIPTION', 'No [ICON_Strength] Combat Strength and [ICON_Movement] Movement penalty when attacking from sea or river.'),
    ('LOC_PROMOTION_ZWEIHANDER_DESCRIPTION', '+7 [ICON_Strength] Combat Strength vs. anti-cavalry unit.'),
    ('LOC_PROMOTION_URBAN_WARFARE_DESCRIPTION', '+10 [ICON_Strength] Combat Strength when having non-ranged combat in district.'),
    ('LOC_PROMOTION_ELITE_GUARD_DESCRIPTION', '+1 additional attack per turn. Can move after attacking.'),
    ('LOC_PROMOTION_VOLLEY_DESCRIPTION', '+5 [ICON_Ranged] Ranged Strength when attacking land unit.'),
    ('LOC_PROMOTION_GARRISON_DESCRIPTION', '+10 [ICON_Strength] Combat Strength when occupying defensive improvement or district.'),
    ('LOC_PROMOTION_ARROW_STORM_DESCRIPTION', '+7 [ICON_Ranged] Ranged Strength when attacking land or naval unit.'),
    ('LOC_PROMOTION_INCENDIARIES_DESCRIPTION', '+7 [ICON_Ranged] Ranged Strength when attacking district defense.'),
    ('LOC_PROMOTION_SUPPRESSION_DESCRIPTION', 'Exercises zone of control.'),
    ('LOC_PROMOTION_EMPLACEMENT_DESCRIPTION', '+10 [ICON_Strength] Combat Strength when defending against district defense.'),
    ('LOC_PROMOTION_EXPERT_MARKSMAN_DESCRIPTION', '+1 additional attack per turn.'),
    ('LOC_PROMOTION_ECHELON_DESCRIPTION', '+5 [ICON_Strength] Combat Strength vs. cavalry unit.'),
    ('LOC_PROMOTION_THRUST_DESCRIPTION', '+5 [ICON_Strength] Combat Strength vs. melee unit.'),
    ('LOC_PROMOTION_SQUARE_DESCRIPTION', 'Double Support bonus.'),
    ('LOC_PROMOTION_SCHILTRON_DESCRIPTION', '+10 [ICON_Strength] Combat Strength when defending against melee unit.'),
    ('LOC_PROMOTION_REDEPLOY_DESCRIPTION', '+1 [ICON_Movement] Movement.'),
    ('LOC_PROMOTION_CHOKE_POINTS_DESCRIPTION', '+7 [ICON_Strength] Combat Strength when defending in Woods, Rainforest, Marsh, or Hills.'),
    ('LOC_PROMOTION_HOLD_THE_LINE_DESCRIPTION', 'Adjacent unit that is not anti-cavalry gets +10 [ICON_Strength] Combat Strength vs. cavalry unit.'),
    ('LOC_PROMOTION_CAPARISON_DESCRIPTION', '+5 [ICON_Strength] Combat Strength vs. anti-cavalry unit.'),
    ('LOC_PROMOTION_COURSERS_DESCRIPTION', '+5 [ICON_Strength] Combat Strength when attacking ranged or siege unit.'),
    ('LOC_PROMOTION_DEPREDATION_DESCRIPTION', 'Pillaging costs only 1 [ICON_Movement] Movement.'),
    ('LOC_PROMOTION_DOUBLE_ENVELOPMENT_DESCRIPTION', 'Double flanking bonus.'),
    ('LOC_PROMOTION_SPIKING_THE_GUNS_DESCRIPTION', '+7 [ICON_Strength] Combat Strength when attacking siege unit.'),
    ('LOC_PROMOTION_PURSUIT_DESCRIPTION', '+1 [ICON_Movement] Movement.'),
    ('LOC_PROMOTION_ESCORT_MOBILITY_DESCRIPTION', 'Formation unit inherits [ICON_Movement] Movement.'),
    ('LOC_PROMOTION_CHARGE_DESCRIPTION', '+10 [ICON_Strength] Combat Strength when attacking fortified unit.'),
    ('LOC_PROMOTION_BARDING_DESCRIPTION', '+7 [ICON_Strength] Combat Strength when defending against ranged attack.'),
    ('LOC_PROMOTION_MARAUDING_DESCRIPTION', '+7 [ICON_Strength] Combat Strength when attacking unit in district.'),
    ('LOC_PROMOTION_ROUT_DESCRIPTION', '+5 [ICON_Strength] Combat Strength when attacking damaged unit.'),
    ('LOC_PROMOTION_ARMOR_PIERCING_DESCRIPTION', '+7 [ICON_Strength] Combat Strength vs. heavy cavalry unit.'),
    ('LOC_PROMOTION_REACTIVE_ARMOR_DESCRIPTION', '+7 [ICON_Strength] Combat Strength when defending against anti-cavalry or heavy cavalry unit.'),
    ('LOC_PROMOTION_BREAKTHROUGH_DESCRIPTION', '+1 additional attack per turn. Can move after attacking.'),
    ('LOC_PROMOTION_GRAPE_SHOT_DESCRIPTION', '+7 [ICON_Strength] Combat Strength vs. land unit.'),
    ('LOC_PROMOTION_CREW_WEAPONS_DESCRIPTION', '+7 [ICON_Strength] Combat Strength when defending.'),
    ('LOC_PROMOTION_SHRAPNEL_DESCRIPTION', '+10 [ICON_Strength] Combat Strength vs. land unit.'),
    ('LOC_PROMOTION_SHELLS_DESCRIPTION', '+10 [ICON_Strength] Combat Strength vs. district defense.'),
    ('LOC_PROMOTION_ADVANCED_RANGEFINDING_DESCRIPTION', '+10 [ICON_Strength] Combat Strength when attacking naval unit.'),
    ('LOC_PROMOTION_EXPERT_CREW_DESCRIPTION', 'Can attack after moving.'),
    ('LOC_PROMOTION_FORWARD_OBSERVERS_DESCRIPTION', '+1 [ICON_Range] Range.'),
    ('LOC_PROMOTION_HELMSMAN_DESCRIPTION', '+1 [ICON_Movement] Movement.'),
    ('LOC_PROMOTION_EMBOLON_DESCRIPTION', '+7 [ICON_Strength] Combat Strength vs. naval unit.'),
    ('LOC_PROMOTION_RUTTER_DESCRIPTION', '+1 sight range.'),
    ('LOC_PROMOTION_REINFORCED_HULL_DESCRIPTION', '+10 [ICON_Strength] Combat Strength when defending against ranged attack.'),
    ('LOC_PROMOTION_CONVOY_DESCRIPTION', '+10 [ICON_Strength] Combat Strength when in formation.'),
    ('LOC_PROMOTION_AUXILIARY_SHIPS_DESCRIPTION', 'Can heal outside friendly territory.'),
    ('LOC_PROMOTION_CREEPING_ATTACK_DESCRIPTION', '+14 [ICON_Strength] Combat Strength vs. naval raider unit.'),
    ('LOC_PROMOTION_LINE_OF_BATTLE_DESCRIPTION', '+7 [ICON_Strength] Combat Strength when attacking naval unit.'),
    ('LOC_PROMOTION_BOMBARDMENT_DESCRIPTION', '+7 [ICON_Strength] Combat Strength when attacking district defense.'),
    ('LOC_PROMOTION_PREPARATORY_FIRE_DESCRIPTION', '+7 [ICON_Strength] Combat Strength when attacking land unit.'),
    ('LOC_PROMOTION_ROLLING_BARRAGE_DESCRIPTION', '+10 [ICON_Strength] Combat Strength when attacking district defense.'),
    ('LOC_PROMOTION_SUPPLY_FLEET_DESCRIPTION', 'Can heal outside friendly territory.'),
    ('LOC_PROMOTION_PROXIMITY_FUSES_DESCRIPTION', '+7 [ICON_Strength] Combat Strength when defending against air attack.'),
    ('LOC_PROMOTION_COINCIDENCE_RANGEFINDING_DESCRIPTION', '+1 [ICON_Range] Range.'),
    ('LOC_PROMOTION_LOOT_DESCRIPTION', '+50 [ICON_Gold] Gold from coastal raid. (on Standard Speed)'),
    ('LOC_PROMOTION_BOARDING_DESCRIPTION', 'When defeating enemy naval unit, gain [ICON_Gold] Gold equal to 100% that unit''s base [ICON_Strength] Combat Strength (on Standard Speed).'),
    ('LOC_PROMOTION_SWIFT_KEEL_DESCRIPTION', '+1 [ICON_Movement] Movement.'),
    ('LOC_PROMOTION_HOMING_TORPEDOES_DESCRIPTION', '+10 [ICON_Strength] Combat Strength vs. naval unit.'),
    ('LOC_PROMOTION_OBSERVATION_DESCRIPTION', '+1 sight range.'),
    ('LOC_PROMOTION_SILENT_RUNNING_DESCRIPTION', 'Can move after attacking.'),
    ('LOC_PROMOTION_WOLFPACK_DESCRIPTION', '+1 additional attack per turn.'),
    ('LOC_PROMOTION_FLIGHT_DECK_DESCRIPTION', '+1 aircraft slot.'),
    ('LOC_PROMOTION_SCOUT_PLANES_DESCRIPTION', '+1 sight range.'),
    ('LOC_PROMOTION_HANGAR_DECK_DESCRIPTION', '+1 aircraft slot.'),
    ('LOC_PROMOTION_ADVANCED_ENGINES_DESCRIPTION', '+1 [ICON_Movement] Movement.'),
    ('LOC_PROMOTION_FOLDING_WINGS_DESCRIPTION', '+1 aircraft slot.'),
    ('LOC_PROMOTION_DECK_CREWS_DESCRIPTION', 'Can heal after attacking.'),
    ('LOC_PROMOTION_SUPER_CARRIER_DESCRIPTION', 'Can heal outside friendly territory.'),
    ('LOC_PROMOTION_DOGFIGHTING_DESCRIPTION', '+7 [ICON_Strength] Combat Strength vs. air fighter unit.'),
    ('LOC_PROMOTION_COCKPIT_ARMOR_DESCRIPTION', '+7 [ICON_Strength] Combat Strength vs. anti-air defense.'),
    ('LOC_PROMOTION_INTERCEPTOR_DESCRIPTION', '+7 [ICON_Strength] Combat Strength vs. air bomber unit.'),
    ('LOC_PROMOTION_STRAFE_DESCRIPTION', '+17 [ICON_Strength] Combat Strength when attacking land unit that is not cavalry.'),
    ('LOC_PROMOTION_GROUND_CREWS_DESCRIPTION', 'Can heal after attacking.'),
    ('LOC_PROMOTION_TANK_BUSTER_DESCRIPTION', '+17 [ICON_Strength] Combat Strength when attacking cavalry unit.'),
    ('LOC_PROMOTION_DROP_TANKS_DESCRIPTION', '+2 [ICON_Range] Range.'),
    ('LOC_PROMOTION_BOX_FORMATION_DESCRIPTION', '+7 [ICON_Strength] Combat Strength vs. air fighter unit.'),
    ('LOC_PROMOTION_EVASIVE_MANEUVERS_DESCRIPTION', '+7 [ICON_Strength] Combat Strength vs. anti-air defense.'),
    ('LOC_PROMOTION_TORPEDO_BOMBER_DESCRIPTION', '+17 [ICON_Strength] Combat Strength when attacking naval unit.'),
    ('LOC_PROMOTION_CLOSE_AIR_SUPPORT_DESCRIPTION', '+12 [ICON_Strength] Combat Strength when attacking land unit.'),
    ('LOC_PROMOTION_TACTICAL_MAINTENANCE_DESCRIPTION', 'Can heal after attacking.'),
    ('LOC_PROMOTION_LONG_RANGE_DESCRIPTION', '+2 [ICON_Range] Range.'),
    ('LOC_PROMOTION_SUPERFORTRESS_DESCRIPTION', 'No minimum health requirement to air pillage.'),
    ('LOC_PROMOTION_MONK_SHADOW_STRIKE_DESCRIPTION', 'Double flanking bonus.'),
    ('LOC_PROMOTION_MONK_TWILIGHT_VEIL_DESCRIPTION', 'Only adjacent enemy unit can reveal this unit.'),
    ('LOC_PROMOTION_MONK_EXPLODING_PALMS_DESCRIPTION', '+10 [ICON_Strength] Combat Strength.'),
    ('LOC_PROMOTION_MONK_DISCIPLES_DESCRIPTION', 'When defeating enemy unit, spread its Religion to nearby cities.'),
    ('LOC_PROMOTION_MONK_SWEEPING_WIND_DESCRIPTION', '+1 additional attack per turn. Can move after attacking.'),
    ('LOC_PROMOTION_MONK_DANCING_CRANE_DESCRIPTION', '+1 [ICON_Movement] Movement.'),
    ('LOC_PROMOTION_MONK_COBRA_STRIKE_DESCRIPTION', '+15 [ICON_Strength] Combat Strength.'),
    ('LOC_PROMOTION_NIHANG_FLANKED_BONUS_DESCRIPTION', '+7 [ICON_Strength] Combat Strength when flanked.'),
    ('LOC_PROMOTION_NIHANG_FAITH_FOR_VICTORIES_DESCRIPTION', 'When defeating enemy unit, gain [ICON_Faith] Faith equal to 50% that unit''s base [ICON_Strength] Combat Strength (on Standard Speed).'),
    ('LOC_PROMOTION_NIHANG_MOVEMENT_BONUS_DESCRIPTION', '+1 [ICON_Movement] Movement.'),
    ('LOC_PROMOTION_NIHANG_NO_WOUNDED_PENALTY_DESCRIPTION', 'No [ICON_Strength] Combat Strength penalty when damaged.'),
    ('LOC_PROMOTION_NIHANG_SUZERAIN_COMBAT_BONUS_DESCRIPTION', '+10 [ICON_Strength] Combat Strength while Suzerain of Lahore.');
