INSERT OR REPLACE INTO EnglishText (Tag, Text) VALUES
    ('LOC_BUILDING_MONUMENT_EXPANSION1_DESCRIPTION', 'Provides +1 Loyalty per turn in this city. If this city has maximum Loyalty, also provides extra +1 [ICON_Culture] Culture.'),
    ('LOC_BUILDING_WATER_MILL_DESCRIPTION', '+1 [ICON_Food] Food on [ICON_RESOURCE_WHEAT] Wheat, [ICON_RESOURCE_RICE] Rice, [ICON_RESOURCE_MAIZE] Maize for this city. Must be built in a city adjacent to River.'),
    ('LOC_BUILDING_FLOOD_BARRIER_DESCRIPTION', 'Protects Coastal Lowland in this city from flooding. Construction cost and per turn maintenance are variable based on the number of Coastal Lowland in this city and the current sea level. Flooded tiles can be fully repaired, but submerged tiles are never recoverable. Must be built in a city with Coastal Lowland.'),
    ('LOC_BUILDING_WALLS_DESCRIPTION', 'Provides district defenses and [ICON_Ranged] Ranged Strikes ability to City Center and Encampment district.[NEWLINE]Provides 1 [ICON_TOURISM] Tourism after Conservation Civic.'),
    ('LOC_BUILDING_CASTLE_EXPANSION2_DESCRIPTION', 'Increases the strength of district defenses. This city is not affected by Battering Rams.[NEWLINE]Provides 2 [ICON_TOURISM] Tourism after Conservation Civic.'),
    ('LOC_BUILDING_STAR_FORT_EXPANSION2_DESCRIPTION', 'Increases the strength of district defenses. This city is not affected by Siege Towers or Battering Rams.[NEWLINE]Provides 3 [ICON_TOURISM] Tourism after Conservation Civic.'),
    ('LOC_BUILDING_MUSEUM_ART_DESCRIPTION', null),
    ('LOC_BUILDING_MUSEUM_ARTIFACT_DESCRIPTION', null),
    ('LOC_BUILDING_SHRINE_DESCRIPTION', 'Allows purchasing Missionaries with [ICON_Faith] Faith.'),
    ('LOC_BUILDING_TEMPLE_DESCRIPTION', 'Allows purchasing Apostles, Gurus, and Inquisitors with [ICON_Faith] Faith.'),
    ('LOC_BUILDING_MOSQUE_DESCRIPTION', 'Missionary and Apostles purchased here can spread Religion 1 extra time.'),
    ('LOC_BUILDING_MARKET_EXPANSION1_DESCRIPTION', '+1 [ICON_TradeRoute] Trade Route capacity.'),
    ('LOC_BUILDING_FACTORY_EXPANSION2_DESCRIPTION', 'Bonus [ICON_Production] Production extends to each City Center within 6 tiles.'),
    ('LOC_BUILDING_COAL_POWER_PLANT_DESCRIPTION', 'Converts [ICON_RESOURCE_COAL] Coal into [ICON_Power] Power as necessary for cities within 6 tiles each turn, at the rate of 1 [ICON_RESOURCE_COAL] Coal [ICON_PowerRight] 4 [ICON_Power] Power.[NEWLINE]Causes heavy CO2 emission into the atmosphere.'),
    ('LOC_BUILDING_FOSSIL_FUEL_POWER_PLANT_DESCRIPTION', 'Converts [ICON_RESOURCE_OIL] Oil into [ICON_Power] Power as necessary for cities within 6 tiles each turn, at the rate of 1 [ICON_RESOURCE_OIL] Oil [ICON_PowerRight] 4 [ICON_Power] Power.[NEWLINE]Bonus [ICON_Production] Production extends to each City Center within 6 tiles.[NEWLINE]Causes Moderate CO2 emission into the atmosphere.'),
    ('LOC_BUILDING_POWER_PLANT_EXPANSION2_DESCRIPTION', 'Converts [ICON_RESOURCE_URANIUM] Uranium into [ICON_Power] Power as necessary for cities within 6 tiles each turn, at the rate of 1 [ICON_RESOURCE_URANIUM] Uranium [ICON_PowerRight] 16 [ICON_Power] Power.[NEWLINE]Bonus [ICON_Production] Production and [ICON_Science] Science extends to each City Center within 6 tiles.[NEWLINE]Causes minor CO2 emission into the atmosphere. There is a chance for a Nuclear Accident to occur, which increases as the reactor ages.'),
    ('LOC_BUILDING_HYDROELECTRIC_DAM_DESCRIPTION', 'Provides +6 [ICON_Power] Power per turn from renewable sources.'),
    ('LOC_BUILDING_ARENA_EXPANSION1_DESCRIPTION', 'Provides +1 [ICON_TOURISM] Tourism after Conservation Civic.'),
    ('LOC_BUILDING_ZOO_EXPANSION1_DESCRIPTION', 'Bonus [ICON_Amenities] Amenity extends to each City Center within 6 tiles.[NEWLINE]+1 [ICON_SCIENCE] Science on Rainforest and Marsh for this city.'),
    ('LOC_BUILDING_STADIUM_EXPANSION1_DESCRIPTION', 'Bonus [ICON_Amenities] Amenity extend to each City Center within 6 tiles.[NEWLINE]+2 [ICON_Tourism] Tourism if the city [ICON_CITIZEN] Population is 10 or higher and +5 [ICON_Tourism] Tourism if the city [ICON_CITIZEN] Population is 20 or higher.'),
    ('LOC_BUILDING_FERRIS_WHEEL_DESCRIPTION', 'Provides +2 [ICON_TOURISM] Tourism.'),
    ('LOC_BUILDING_AQUARIUM_DESCRIPTION', 'Bonus [ICON_Amenities] Amenity extends to each City Center within 9 tiles.[NEWLINE]+1 [ICON_SCIENCE] Science on sea Resource, Shipwreck, and Reef for this city.'),
    ('LOC_BUILDING_AQUATICS_CENTER_DESCRIPTION', 'Bonus [ICON_Amenities] Amenity extend to each City Center within 9 tiles.[NEWLINE]+2 [ICON_Tourism] Tourism for each Wonder built on or adjacent to Coast for this city.'),
    ('LOC_BUILDING_BARRACKS_EXPANSION2_DESCRIPTION', '+25% combat experience for all melee and ranged units trained in this city.[NEWLINE]Strategic Resource Stockpiles increased +10 (on Standard Speed).'),
    ('LOC_BUILDING_STABLE_EXPANSION2_DESCRIPTION', '+25% combat experience for all cavalry and siege units trained in this city.[NEWLINE]Strategic Resource Stockpiles increased +10 (on Standard Speed).'),
    ('LOC_BUILDING_ARMORY_EXPANSION2_DESCRIPTION', '+25% combat experience for all land units trained in this city.[NEWLINE]Strategic Resource Stockpiles increased +10 (on Standard Speed).'),
    ('LOC_BUILDING_MILITARY_ACADEMY_EXPANSION2_DESCRIPTION', '+25% combat experience for all land units trained in this city. Allows Corps and Armies to be trained directly (-25% cost).[NEWLINE]Strategic Resource Stockpiles increased +10 (on Standard Speed).'),
    ('LOC_BUILDING_LIGHTHOUSE_EXPANSION2_DESCRIPTION', '+25% combat experience for all naval units trained in this city.[NEWLINE]+1 [ICON_FOOD] Food on Coast for this city. +2 [ICON_HOUSING] Housing if this city is adjacent to Coast.[NEWLINE]+1 [ICON_TradeRoute] Trade Route capacity, if this city does not have Market building.'),
    ('LOC_BUILDING_SHIPYARD_EXPANSION2_DESCRIPTION', '+25% combat experience for all naval units trained in this city.[NEWLINE]+1 [ICON_PRODUCTION] Production on unimproved Coast and Lake for this city.'),
    ('LOC_BUILDING_SEAPORT_DESCRIPTION', '+25% combat experience for all naval units trained in this city. Allows Fleets and Armadas to be trained directly (-25% cost).[NEWLINE]+2 [ICON_GOLD] Gold on Coast for this city.'),
    ('LOC_BUILDING_HANGAR_DESCRIPTION', '+25% combat experience for air units trained in this city. +1 air unit slot.'),
    ('LOC_BUILDING_AIRPORT_DESCRIPTION', '+50% combat experience for air units trained in this city. +1 air unit slot.[NEWLINE]Can transport land units after Rapid Deployment Civic.');
