INSERT OR REPLACE INTO EnglishText (Tag, Text) VALUES
    ('LOC_GOSSIP_SOURCE_RUMOR', 'Rumor:'),
    ('LOC_GOSSIP_SOURCE_TECH', 'Newspaper:'),
    ('LOC_GOSSIP_SOURCE_TRADER', 'Trader:'),
    ('LOC_GOSSIP_SOURCE_DELEGATE', 'Diplomat:'),
    ('LOC_GOSSIP_SOURCE_TRAIT', 'Flying Squadron:'),
    ('LOC_GOSSIP_SOURCE_ALLY', 'Ally Report:'),
    ('LOC_GOSSIP_SOURCE_SPY', 'Spy:'),
    ('LOC_GOSSIP_SOURCE_GREAT_PERSON_JOURNALISM', 'M. K. Goddard:'),
    ('LOC_GOSSIP_SOURCE_VENDOR', 'Örtöö:'),
    ('LOC_GOSSIP_SOURCE_HIGHLEVEL_SPY', 'Spy Leader:'),
    ('LOC_GOSSIP_AGENDA_KUDOS', '{1_LeaderName} thanked {2_Leadername} for cooperation. (Agenda: {3_AgendaName}).'),
    ('LOC_GOSSIP_AGENDA_WARNING', '{1_LeaderName} warned {2_Leadername} about violation. (Agenda: {3_AgendaName}).'),
    ('LOC_GOSSIP_ALLIED', '{1_CivName} formed an alliance with {2_CivName}.'),
    ('LOC_GOSSIP_ARTIFACT_EXTRACTED', '{1_CivName} excavated an artifact: {2_GreatWork}.'),
    ('LOC_GOSSIP_BARBARIAN_INVASION_STARTED', '{1_CivName} is facing a barbarian invasion at {2_CityName}.'),
    ('LOC_GOSSIP_BARBARIAN_RAID_STARTED', '{1_CivName} is facing a barbarian raid at {2_CityName}.'),
    ('LOC_GOSSIP_BEACH_RESORT_CREATED', '{1_CivName} built a seaside resort outside {2_CityName}.'),
    ('LOC_GOSSIP_CHANGE_GOVERNMENT', '{1_CivName} switched governments to {2_Government}.'),
    ('LOC_GOSSIP_CITY_BESIEGED', '{1_CityName} is facing a siege.'),
    ('LOC_GOSSIP_CITY_LIBERATED', '{1_CivName} liberated {2_CityName} and returned it to {3_CivName}.'),
    ('LOC_GOSSIP_CITY_RAZED', '{1_CivName} razed a city founded by {2_CivName}.'),
    ('LOC_GOSSIP_CLEAR_CAMP', '{1_CivName} used {LOC_GRAMMAR_A_AN << {2_UnitName}} to clear {LOC_GRAMMAR_A_AN << {3_ImprovementName}}.'),
    ('LOC_GOSSIP_CITY_STATE_INFLUENCE', '{1_CivName} sent an Envoy to {2_CityState}.'),
    ('LOC_GOSSIP_CONQUER_CITY', '{1_CivName} conquered {2_CityName}.'),
    ('LOC_GOSSIP_CONSTRUCT_BUILDING', '{1_CivName} built {LOC_GRAMMAR_A_AN << {2_BuildingName}} in {3_CityName}.'),
    ('LOC_GOSSIP_CONSTRUCT_DISTRICT', '{1_CivName} built {LOC_GRAMMAR_A_AN << {2_DistrictName}} in {3_CityName}.'),
    ('LOC_GOSSIP_CREATE_PANTHEON', '{1_CivName} is worshipping a Pantheon: {2_BeliefName}.'),
    ('LOC_GOSSIP_CULTURVATE_CIVIC', '{1_CivName} completed development of {2_CivicName}.'),
    ('LOC_GOSSIP_DECLARED_FRIENDSHIP', '{1_CivName} is now friends with {2_CivName}.'),
    ('LOC_GOSSIP_DELEGATION', '{1_CivName} received a foreign delegation from {2_CivName}.'),
    ('LOC_GOSSIP_DENOUNCED', '{1_CivName} denounced {2_CivName}.'),
    ('LOC_GOSSIP_EMBASSY', '{1_CivName} granted establishment of embassy from {2_CivName}.'),
    ('LOC_GOSSIP_ERA_CHANGED', '{1_CivName} progressed to the {3_NewEra}.'),
    ('LOC_GOSSIP_FIND_NATURAL_WONDER', '{1_CivName} discovered the {2_NWName} natural wonder.'),
    ('LOC_GOSSIP_FOUND_CITY', '{1_CivName} founded a new city named: {2_CityName}.'),
    ('LOC_GOSSIP_FOUND_RELIGION', '{1_CivName} founded a new Religion: {2_ReligionName}.'),
    ('LOC_GOSSIP_GREATPERSON_CREATED', '{1_CivName} earned the {2_unit} {3_GreatPerson}.'),
    ('LOC_GOSSIP_LAUNCHING_ATTACK', '{1_CivName} launched a military assault on {2_CivName}.'),
    ('LOC_GOSSIP_WAR_PREPARATION', '{1_CivName} is considering a war on {2_CivName}.'),
    ('LOC_GOSSIP_INQUISITION_LAUNCHED', '{1_CivName} launched an inquisition in name of {2_ReligionName}.'),
    ('LOC_GOSSIP_LAND_UNIT_LEVEL', '{1_CivName} has {LOC_GRAMMAR_A_AN << {2_UnitName}} that earned the {3_PromotionName} promotion.'),
    ('LOC_GOSSIP_MAKE_DOW', '{1_CivName} declared war on {2_OtherPlayer}!'),
    ('LOC_GOSSIP_NATIONAL_PARK_CREATED', '{1_CivName} created {2_NationalParkName}.'),
    ('LOC_GOSSIP_NAVAL_UNIT_LEVEL', '{1_CivName} has {LOC_GRAMMAR_A_AN << {2_UnitName}} that earned the {3_PromotionName} promotion.'),
    ('LOC_GOSSIP_NEW_RELIGIOUS_MAJORITY', '{1_CivName} has {2_ReligionName} as dominant religion.'),
    ('LOC_GOSSIP_PILLAGE', '{1_CivName} pillaged an enemy {2_TargetName} with {LOC_GRAMMAR_A_AN << {3_UnitName}}.'),
    ('LOC_GOSSIP_POLICY_ENACTED', '{1_CivName} adopted the {2_SlotName} policy {3_PolicyName}.'),
    ('LOC_GOSSIP_RECEIVE_DOW', '{1_CivName} received a declaration of war from {2_OtherPlayer}!'),
    ('LOC_GOSSIP_RELIC_RECEIVED', '{1_CivName} gained the religious relic: {2_RelicName}.'),
    ('LOC_GOSSIP_RESEARCH_AGREEMENT', '{1_CivName} and {2_CivName} formed a scientific partnership.'),
    ('LOC_GOSSIP_RESEARCH_TECH', '{1_CivName} completed research on {2_TechName}'),
    ('LOC_GOSSIP_SPY_DISRUPT_ROCKETRY_DETECTED', '{1_CivName} had Spaceport in {2_CityName} sabotaged by {3_SpyPlayer}.'),
    ('LOC_GOSSIP_SPY_DISRUPT_ROCKETRY_UNDETECTED', '{1_CivName} had Spaceport in {2_CityName} sabotaged.'),
    ('LOC_GOSSIP_SPY_GREAT_WORK_HEIST_DETECTED', '{1_CivName} had Great Work in {2_CityName} stolen by {3_SpyPlayer}.'),
    ('LOC_GOSSIP_SPY_GREAT_WORK_HEIST_UNDETECTED', '{1_CivName} had Great Work in {2_CityName} stolen.'),
    ('LOC_GOSSIP_SPY_RECRUIT_PARTISANS_DETECTED', '{1_CivName} is dealing with partisans in {2_CityName} recruited by {3_SpyPlayer}.'),
    ('LOC_GOSSIP_SPY_RECRUIT_PARTISANS_UNDETECTED', '{1_CivName} is dealing with partisans in {2_CityName}.'),
    ('LOC_GOSSIP_SPY_SABOTAGE_PRODUCTION_DETECTED', '{1_CivName} had Industrial Zone in {2_CityName} sabotaged by {3_SpyPlayer}.'),
    ('LOC_GOSSIP_SPY_SABOTAGE_PRODUCTION_UNDETECTED', '{1_CivName} had Industrial Zone in {2_CityName} sabotaged.'),
    ('LOC_GOSSIP_SPY_SIPHON_FUNDS_DETECTED', '{1_CivName} had funds stolen in {2_CityName} by {3_SpyPlayer}.'),
    ('LOC_GOSSIP_SPY_SIPHON_FUNDS_UNDETECTED', '{1_CivName} had funds stolen in {2_CityName}.'),
    ('LOC_GOSSIP_SPY_STEAL_TECH_BOOST_DETECTED', '{1_CivName} had technology stolen in {2_CityName} by {3_SpyPlayer}.'),
    ('LOC_GOSSIP_SPY_STEAL_TECH_BOOST_UNDETECTED', '{1_CivName} had technology stolen in {2_CityName}.'),
    ('LOC_GOSSIP_TRADE_DEAL', '{1_CivName} is trading with {2_CivName}.'),
    ('LOC_GOSSIP_TRADE_RENEGE', '{1_CivName} reneged a deal with {2_CivName}.'),
    ('LOC_GOSSIP_TRAIN_SETTLER', '{1_CivName} created a new {2_UnitName}.'),
    ('LOC_GOSSIP_TRAIN_UNIT', '{1_CivName} created world''s first {2_UnitName}.'),
    ('LOC_GOSSIP_TRAIN_UNIQUE_UNIT', '{1_CivName} created unique unit: the {2_UnitName}.'),
    ('LOC_GOSSIP_SPACE_RACE_PROJECT_COMPLETED', '{1_CivName} completed Space Race project: {2_ProjectType}.'),
    ('LOC_GOSSIP_WMD_BUILT', '{1_CivName} built {2_WMDCount} WMDs!'),
    ('LOC_GOSSIP_WMD_STRIKE', '{1_CivName} unleashed a WMD! A {2_UnitName}!'),
    ('LOC_GOSSIP_WONDER_STARTED', '{1_CivName} began construction on the {3_BuildingName} in {2_CityName}.'),
    ('LOC_GOSSIP_ANARCHY_BEGINS', '{1_CivName} had a coup d''état removing {2_Government}, starting anarchy.'),
    ('LOC_GOSSIP_PROJECT_STARTED', '{1_CivName} has started {2_ProjectType}.'),
    ('LOC_GOSSIP_CONQUER_CAPITAL_CITY', '{1_CivName} has conquered {3_CityName}, the original capital of {2_CivName}.'),
    ('LOC_GOSSIP_START_VICTORY_STRATEGY', '{1_CivName} is seeking {2_VictoryName}.'),
    ('LOC_GOSSIP_STOP_VICTORY_STRATEGY', '{1_CivName} is no longer seeking {2_VictoryType}.'),
    ('LOC_GOSSIP_SPY_FOMENT_UNREST_DETECTED', '{1_CivName} lost loyalty in {2_CityName} by {3_SpyPlayer}.'),
    ('LOC_GOSSIP_SPY_FOMENT_UNREST_UNDETECTED', '{1_CivName} lost loyalty in {2_CityName}.'),
    ('LOC_GOSSIP_SPY_NEUTRALIZE_GOVERNOR_DETECTED', '{1_CivName} had governor in {2_CityName} neutralized by {3_SpyPlayer}.'),
    ('LOC_GOSSIP_SPY_NEUTRALIZE_GOVERNOR_UNDETECTED', '{1_CivName} had governor in {2_CityName} neutralized.'),
    ('LOC_GOSSIP_SPY_DAM_BREACHED_DETECTED', '{1_CivName} had Dam breached in {2_CityName} by {3_SpyPlayer}.'),
    ('LOC_GOSSIP_SPY_DAM_BREACHED_UNDETECTED', '{1_CivName} had Dam breached in {2_CityName}.'),
    ('LOC_GOSSIP_ROCK_CONCERT', '{3_BandName}''s concert in {1_City_Name} earned a review: "{2_ResultName}".'),
    ('LOC_GOSSIP_POWERED_CITY', '{1_CivName} is now powering {2_CityName} with electricity.'),
    ('LOC_GOSSIP_RANDOM_EVENT', '{1_CivName} has suffered significant damage from {2_NaturalDisasterName}.');
